name: Bot 12
on:
  workflow_dispatch:
    inputs:
      target_ip:
        required: true
      target_port:
        required: true
      threads:
        required: true
        default: '1000'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python udp_worker.py
        env:
          TARGET_IP: ${{ github.event.inputs.target_ip }}
          TARGET_PORT: ${{ github.event.inputs.target_port }}
          THREADS: ${{ github.event.inputs.threads }}
